//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaz_Okulu_MVC_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruTablosu
    {
        public int BasvuruID { get; set; }
        public Nullable<int> BasOgrID { get; set; }
        public Nullable<int> BasDersId { get; set; }
        public Nullable<int> BasOgrtID { get; set; }
    
        public virtual DersTablosu DersTablosu { get; set; }
        public virtual ÖğrenciTablosu ÖğrenciTablosu { get; set; }
    }
}
