//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaz_Okulu_MVC_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DersTablosu()
        {
            this.BasvuruTablosu = new HashSet<BasvuruTablosu>();
            this.ÖğretmenTablosu = new HashSet<ÖğretmenTablosu>();
        }
    
        public int DersID { get; set; }
        public string DersAd { get; set; }
        public Nullable<int> MaxKont { get; set; }
        public Nullable<int> MinKont { get; set; }
        public Nullable<int> OgrSayısı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruTablosu> BasvuruTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÖğretmenTablosu> ÖğretmenTablosu { get; set; }
    }
}
