//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaz_Okulu_MVC_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ÖğretmenTablosu
    {
        public int OgrtID { get; set; }
        public string OgrtAdSoyad { get; set; }
        public Nullable<int> OgrtDersID { get; set; }
    
        public virtual DersTablosu DersTablosu { get; set; }
    }
}
